# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: picpay
      POSTGRES_USER: picpay
      POSTGRES_DB: picpay
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  configure_db:
    build: ./database
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: dbname
      PGPASSWORD: passwd
      SET_USERS: 'true'
      SET_PRIORITY: 'true'
      CREATE_DATABASE: 'true'

  web:
    build: .
    command: npm start
    volumes:
      - ./priority:/src/database/priority/
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - configure_db
    environment:
      DB_HOST: postgres
      DB_USER: picpay
      DB_PASSWORD: picpay
      DB_SCHEMA: picpay
